# Generated by Django 3.0.4 on 2020-04-11 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('spad', 'superadmin'), ('ad', 'admin'), ('cus', 'customer')], default='cus', max_length=4)),
                ('status', models.CharField(choices=[('act', 'active'), ('pend', 'pending'), ('blk', 'blocked')], default='act', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
