# Generated by Django 3.0.4 on 2020-04-15 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255)),
                ('pages', models.IntegerField(default=0)),
                ('score_rate', models.FloatField(default=0)),
                ('total_rate', models.IntegerField(default=0)),
                ('image_src', models.ImageField(blank=True, default='static/uploads/default.png', null=True, upload_to='static/uploads/images')),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_books', to='books.Category')),
            ],
        ),
    ]
