# Generated by Django 3.0.5 on 2020-04-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200412_0646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Rate'), (1, 'Comment'), (2, 'read'), (3, 'Favorite'), (4, 'Follow'), (5, 'Request'), (6, 'Like')], default=0),
        ),
    ]
