# Generated by Django 3.0.4 on 2020-04-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
