# Generated by Django 3.0.5 on 2020-04-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200414_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Rate'), (1, 'Comment'), (2, 'Read'), (3, 'Favorite'), (4, 'Follow'), (5, 'Buy'), (6, 'Like')], default=0),
        ),
    ]
