# Generated by Django 3.0.4 on 2020-04-21 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_action', models.DateTimeField(auto_now_add=True)),
                ('content_action', models.CharField(max_length=255)),
                ('type_action', models.CharField(choices=[('add', 'added'), ('rated', 'rated'), ('edited', 'edited'), ('responded', 'responded'), ('deleted', 'deleted'), ('removed', 'removed')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_action', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
